/* Exemple 4: Amb paràmetres %TYPE*/
/* Database: HR */
CREATE OR REPLACE FUNCTION p_INSERTDEPARTMENTS(ID DEPARTMENTS.DEPARTMENT_ID%TYPE,							   NOM DEPARTMENTS.DEPARTMENT_NAME%TYPE,          				   LOC DEPARTMENTS.LOCATION_ID%TYPE) RETURNS void 
LANGUAGE plpgsql AS $$
BEGIN
   IF NOM IS NOT NULL THEN 
      INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID) 
      VALUES (ID, NOM, LOC);
   END IF;
END;$$;

/**Exemple utilitzacio**/

SELECT p_INSERTDEPARTMENTS(165,'COMPRES',1700);
